### ISSUE TITLE
Integrate with Homebrew

### ISSUE THREAD

**Issue by jeroenleenarts** [njdehoog/Spelt#2]
Would be great to install and update Spelt through home-brew. Just like say Swiftlint for example. This is Swiftlint's recipe: https://github.com/Homebrew/homebrew-core/blob/7dfe465b7cb48be58bedc4349a5357953a53133e/Formula/swiftlint.rb

**Comment by njdehoog** [comment]
Good idea @jeroenleenarts. I'd like to first be able to ship a compiled binary (See issue https://github.com/njdehoog/Spelt/issues/1), because the project has a lot of dependencies, and it takes a long time to build from source. I would like to add homebrew support afterwards as well though.

**Comment by njdehoog** [comment]
I looked into this, but it seems like integrating with Homebrew is difficult when using Carthage for dependency management, unless we can figure out a way to only ship a precompiled binary using Homebrew, which I haven't been able to do (yet). Since spelt can be installed using the [package installer](https://github.com/njdehoog/Spelt/releases) as well, I don't think Homebrew support is a priority, but feel free to investigate further.

This is the formula I was using:

``` ruby
class Spelt < Formula
  desc "Delightfully simple static site generator written in Swift"
  homepage "https://github.com/njdehoog/Spelt"
  url "https://github.com/njdehoog/Spelt/archive/0.1.1.tar.gz"
  version "0.1.1"
  sha256 "59304098c6ea856b26adab1aae3ffaf74b5b6e7d3c3ea7ce8b23de53e1311588"

  depends_on :xcode => ["8.0", :build]
  depends_on "carthage" => :build

  def install
    system "make", "bootstrap"
    system "make", "prefix_install", "PREFIX=#{prefix}"
  end

  test do
    system "#{bin}/spelt", "help"
  end
end
```
